vmware/sql-to-dbsp-compiler

SQL-compiler/src/main/java/org/dbsp/sqlCompiler/dbsp/TypeCompiler.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/dbsp/circuit/expression/DBSPLiteral.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/dbsp/circuit/type/DBSPTypeDouble.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/dbsp/circuit/type/DBSPTypeFloat.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/dbsp/circuit/type/DBSPTypeInteger.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/dbsp/circuit/type/DBSPTypeString.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/frontend/CalciteCompiler.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/frontend/SqlSimulator.java
SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/EndToEndTests.java

Basic support for nullable columns

---

SQL-compiler/src/main/java/org/dbsp/sqlCompiler/dbsp/CalciteToDBSPCompiler.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/dbsp/DBSPTransaction.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/dbsp/ExpressionCompiler.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/dbsp/circuit/DBSPCircuit.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/dbsp/circuit/SqlRuntimeLibrary.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/dbsp/circuit/expression/DBSPComment.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/dbsp/circuit/expression/DBSPLiteral.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/dbsp/circuit/expression/DBSPRawTupleExpression.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/dbsp/circuit/expression/DBSPZSetLiteral.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/dbsp/circuit/type/DBSPTypeNull.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/dbsp/circuit/type/DBSPTypeRawTuple.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/frontend/CalciteCompiler.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/frontend/CalciteProgram.java
SQL-compiler/src/main/java/org/dbsp/sqllogictest/DBSPExecutor.java
SQL-compiler/src/main/java/org/dbsp/sqllogictest/Main.java
SQL-compiler/src/main/java/org/dbsp/sqllogictest/SqlTestFile.java
SQL-compiler/src/main/java/org/dbsp/sqllogictest/SqlTestOutputDescription.java
SQL-compiler/src/main/java/org/dbsp/sqllogictest/SqlTestQuery.java
SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/CalciteCompilerTests.java
SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/DBSPCompilerTests.java
SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/EndToEndTests.java
SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/IRTests.java

(Almost) end-to-end testing for sqllogictest

---

SQL-compiler/src/main/java/org/dbsp/sqlCompiler/dbsp/circuit/DBSPCircuit.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/dbsp/circuit/SqlRuntimeLibrary.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/dbsp/circuit/expression/DBSPEnumValue.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/frontend/CalciteCompiler.java
SQL-compiler/src/main/java/org/dbsp/sqllogictest/DBSPExecutor.java
SQL-compiler/src/main/java/org/dbsp/sqllogictest/Main.java
SQL-compiler/src/main/java/org/dbsp/sqllogictest/SqlTestFile.java
SQL-compiler/src/main/java/org/dbsp/sqllogictest/SqlTestOutputDescription.java
SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/EndToEndTests.java
lib/hashing/Cargo.toml
lib/hashing/src/lib.rs
temp/Cargo.toml

sqllogictest check MD5 checksum

---

SQL-compiler/src/main/java/org/dbsp/sqlCompiler/dbsp/ExpressionCompiler.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/dbsp/circuit/SqlRuntimeLibrary.java
SQL-compiler/src/main/java/org/dbsp/sqllogictest/Main.java
SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/EndToEndTests.java
lib/sqllibbool/Cargo.toml
lib/sqllibbool/src/lib.rs
lib/sqlvalue/Cargo.toml
temp/Cargo.toml

Handle aggregates in FP

---

SQL-compiler/src/main/java/org/dbsp/sqlCompiler/dbsp/CalciteToDBSPCompiler.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/dbsp/ExpressionCompiler.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/dbsp/JoinConditionAnalyzer.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/dbsp/circuit/SqlRuntimeLibrary.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/dbsp/circuit/operator/DBSPFlatMapOperator.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/dbsp/circuit/operator/DBSPJoinOperator.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/dbsp/rust/expression/DBSPApplyExpression.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/dbsp/rust/expression/DBSPBlockExpression.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/dbsp/rust/expression/DBSPClosureExpression.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/dbsp/rust/expression/DBSPMatchExpression.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/dbsp/rust/expression/DBSPRawTupleExpression.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/dbsp/rust/expression/DBSPSomeExpression.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/dbsp/rust/path/DBSPPath.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/dbsp/rust/path/DBSPPathSegment.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/dbsp/rust/path/DBSPSimplePathSegment.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/dbsp/rust/path/package-info.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/dbsp/rust/pattern/DBSPTuplePattern.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/dbsp/rust/pattern/DBSPTupleStructPattern.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/dbsp/rust/pattern/DBSPWildcardPattern.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/dbsp/rust/type/DBSPTypeFP.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/dbsp/rust/type/DBSPTypeRawTuple.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/dbsp/rust/type/DBSPTypeRef.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/dbsp/rust/type/DBSPTypeTuple.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/frontend/CalciteCompiler.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/frontend/SqlSimulator.java
SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/EndToEndTests.java

This also introduces several more classes that model Rust constructs, such as Paths and Patterns.

Efficient implementation for equijoins

---

SQL-compiler/src/main/java/org/dbsp/sqlCompiler/dbsp/CalciteToDBSPCompiler.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/dbsp/JoinConditionAnalyzer.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/dbsp/circuit/operator/DBSPDistinctOperator.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/dbsp/circuit/operator/DBSPJoinOperator.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/dbsp/circuit/operator/DBSPNegateOperator.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/dbsp/circuit/operator/DBSPOperator.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/dbsp/circuit/operator/DBSPSubtractOperator.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/dbsp/circuit/operator/DBSPSumOperator.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/dbsp/rust/expression/DBSPFieldExpression.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/dbsp/rust/expression/DBSPRawTupleExpression.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/dbsp/rust/expression/DBSPTupleExpression.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/dbsp/rust/type/DBSPTypeRef.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/dbsp/rust/type/DBSPTypeTuple.java
SQL-compiler/src/main/java/org/dbsp/sqllogictest/Main.java
SQL-compiler/src/main/java/org/dbsp/util/Linq.java
SQL-compiler/src/main/java/org/dbsp/util/Utilities.java
SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/EndToEndTests.java

Support for outer joins

---

SQL-compiler/src/main/java/org/dbsp/sqlCompiler/dbsp/CalciteToDBSPCompiler.java

Fix incorrect comment

---

SQL-compiler/pom.xml
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/dbsp/CalciteToDBSPCompiler.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/frontend/CalciteCompiler.java
SQL-compiler/src/main/java/org/dbsp/sqllogictest/Main.java
SQL-compiler/src/main/java/org/dbsp/sqllogictest/SqlTestFile.java
SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/EndToEndTests.java

Better use of the Calcite optimizer

---

SQL-compiler/src/main/java/org/dbsp/sqlCompiler/dbsp/CalciteToDBSPCompiler.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/frontend/CalciteCompiler.java
SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/EndToEndTests.java

Fight with the Calcite optimizer

---

SQL-compiler/src/main/java/org/dbsp/sqlCompiler/dbsp/CalciteToDBSPCompiler.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/dbsp/DBSPTransaction.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/frontend/CalciteCompiler.java
SQL-compiler/src/main/java/org/dbsp/sqllogictest/Main.java
SQL-compiler/src/main/java/org/dbsp/sqllogictest/RustTestGenerator.java
SQL-compiler/src/main/java/org/dbsp/sqllogictest/SqlTestFile.java
SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/EndToEndTests.java

Support more SLT tests and optimize queries better

---

SQL-compiler/src/main/java/org/dbsp/sqlCompiler/dbsp/ExpressionCompiler.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/dbsp/circuit/SqlRuntimeLibrary.java
SQL-compiler/src/main/java/org/dbsp/sqllogictest/Main.java
lib/sqllib/src/lib.rs

Fix implementation of a few Calcite row expression operators

---

README.md
SQL-compiler/pom.xml
SQL-compiler/src/main/java/org/dbsp/sqllogictest/Main.java
SQL-compiler/src/main/java/org/dbsp/sqllogictest/executors/DBSPExecutor.java
SQL-compiler/src/main/java/org/dbsp/sqllogictest/executors/JDBCExecutor.java
SQL-compiler/src/main/java/org/dbsp/sqllogictest/executors/NoExecutor.java
SQL-compiler/src/main/java/org/dbsp/sqllogictest/executors/SqlTestExecutor.java
SQL-compiler/src/main/java/org/dbsp/util/Utilities.java
SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/EndToEndTests.java
lib/hashing/src/lib.rs

JDBC executor SqlLogicTest implementation

---

README.md
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/dbsp/CalciteToDBSPCompiler.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/dbsp/DBSPTransaction.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/dbsp/ExpressionCompiler.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/frontend/CalciteCompiler.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/frontend/Catalog.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/frontend/CreateTableStatement.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/frontend/DropTableStatement.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/frontend/SqlSimulator.java
SQL-compiler/src/main/java/org/dbsp/sqllogictest/Main.java
SQL-compiler/src/main/java/org/dbsp/sqllogictest/SqlStatement.java
SQL-compiler/src/main/java/org/dbsp/sqllogictest/SqlStatementList.java
SQL-compiler/src/main/java/org/dbsp/sqllogictest/SqlTestFile.java
SQL-compiler/src/main/java/org/dbsp/sqllogictest/SqlTestQuery.java
SQL-compiler/src/main/java/org/dbsp/sqllogictest/executors/DBSPExecutor.java
SQL-compiler/src/main/java/org/dbsp/sqllogictest/executors/DBSP_JDBC_Executor.java
SQL-compiler/src/main/java/org/dbsp/sqllogictest/executors/JDBCExecutor.java
SQL-compiler/src/main/java/org/dbsp/sqllogictest/executors/SqlTestExecutor.java
SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/DBSPCompilerTests.java
SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/EndToEndTests.java

Hybrid JDBC/DBSP test executor

---

README.md
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/midend/ExpressionCompiler.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/midend/TypeCompiler.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/ToRustInnerVisitor.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/InnerVisitor.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/literal/DBSPIntervalLiteral.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/literal/DBSPKeywordLiteral.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/primitive/DBSPTypeInterval.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/primitive/DBSPTypeKeyword.java
SQL-compiler/src/main/java/org/dbsp/sqllogictest/Main.java
SQL-compiler/src/main/java/org/dbsp/sqllogictest/executors/DBSPExecutor.java
SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/ComplexQueriesTest.java

Define primitive types for intervals and keywords

---

README.md
SQL-compiler/sltbugs.txt
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/DBSPCircuit.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/CalciteCompiler.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/statements/CreateRelationStatement.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/midend/CalciteToDBSPCompiler.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/midend/ExpressionCompiler.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/midend/JoinConditionAnalyzer.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/optimizer/CircuitOptimizer.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/FunctorVisitor.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/NoIntegralVisitor.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/OptimizeIncrementalVisitor.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/ToCsvVisitor.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/ToDotVisitor.java
SQL-compiler/src/main/java/org/dbsp/sqllogictest/AcceptancePolicy.java
SQL-compiler/src/main/java/org/dbsp/sqllogictest/ExecutionOptions.java
SQL-compiler/src/main/java/org/dbsp/sqllogictest/Main.java
SQL-compiler/src/main/java/org/dbsp/sqllogictest/SqlTestFile.java
SQL-compiler/src/main/java/org/dbsp/sqllogictest/executors/DBSPExecutor.java
SQL-compiler/src/main/java/org/dbsp/sqllogictest/executors/DBSP_JDBC_Executor.java
SQL-compiler/src/main/java/org/dbsp/sqllogictest/executors/JDBCExecutor.java
SQL-compiler/src/main/java/org/dbsp/sqllogictest/executors/SqlTestExecutor.java
SQL-compiler/src/main/java/org/dbsp/util/Logger.java
SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/EndToEndTests.java
SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/OtherTests.java

Fix bugs discovered by the evidence tests

---

SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/RemoveOperatorsVisitor.java
SQL-compiler/src/main/java/org/dbsp/sqllogictest/ExecutionOptions.java
SQL-compiler/src/main/java/org/dbsp/sqllogictest/Main.java
SQL-compiler/src/main/java/org/dbsp/sqllogictest/executors/DBSPExecutor.java
SQL-compiler/src/main/java/org/dbsp/sqllogictest/executors/DBSP_JDBC_Executor.java
SQL-compiler/src/main/java/org/dbsp/sqllogictest/executors/JDBCExecutor.java
SQL-compiler/src/main/java/org/dbsp/sqllogictest/executors/SqlTestExecutor.java

Fix bug in RemoveOperationsVisitor

---

SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/CalciteToDBSPCompiler.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/ExpressionCompiler.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/JoinConditionAnalyzer.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/sqlparser/CalciteCompiler.java
SQL-compiler/src/main/java/org/dbsp/sqllogictest/Main.java
SQL-compiler/src/main/java/org/dbsp/sqllogictest/executors/SqlTestExecutor.java
SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/EndToEndTests.java
SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/NaiveIncrementalTests.java
SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/TimeTests.java
lib/sqllib/src/lib.rs
temp/Cargo.toml

Fix calcite compiler to perform constant folding

---

SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/sqlparser/CalciteCompiler.java
SQL-compiler/src/main/java/org/dbsp/sqllogictest/Main.java
SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/EndToEndTests.java
SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/NaiveIncrementalTests.java

Handle all divisions in an expression in the same way

---

SQL-compiler/sql-to-dbsp

Modified the script so it can be invoked from any directory.

Invoke sql-to-dbsp from any location.

---

SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/TimeTests.java
lib/sqllib/src/casts.rs

Support for a few timestamp casts

---

SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/ToRustVisitor.java
SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/ComplexQueriesTest.java

Fixes #83 
Have to figure out whether this is always the right choice.

use 'unwrap_or_default' for window aggregates

---

SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/SqlRuntimeLibrary.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/CompilerOptions.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/CalciteToDBSPCompiler.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/ExpressionCompiler.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/sqlparser/CalciteCompiler.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/DBSPCompiler.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/literal/DBSPI64Literal.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/literal/DBSPKeywordLiteral.java
SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/BaseSQLTests.java
SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/postgres/PostgresDateTests.java
lib/sqllib/src/lib.rs
lib/sqllib/src/timestamp.rs

Support for date operations with tests from Postgres

---

.github/workflows/ci.yml

Avoid running redundant CI workflows

---

SQL-compiler/src/main/java/org/dbsp/sqlCompiler/circuit/SqlRuntimeLibrary.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/ExpressionCompiler.java
SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/EndToEndTests.java
lib/sqllib/src/casts.rs
lib/sqllib/src/lib.rs

Support for string concatenation with ||

---

doc/README.rst

Signed-off-by: Lalith Suresh <lsuresh@vmware.com>

Add instructions to build docs/ folder on Apple hardware

---

SQL-compiler/src/main/java/org/dbsp/sqlCompiler/Main.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/CompilerOptions.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/errors/CompilerMessages.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/errors/SourceFileContents.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/errors/SourcePosition.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/errors/SourcePositionRange.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/errors/package-info.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/ExpressionCompiler.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/DBSPCompiler.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/ThreeOperandVisitor.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/ToCsvVisitor.java
SQL-compiler/src/main/java/org/dbsp/sqllogictest/executors/DBSPExecutor.java
SQL-compiler/src/main/java/org/dbsp/util/Unimplemented.java
SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/ComplexQueriesTest.java
SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/OtherTests.java
doc/README.rst

Emit nicer error messages

---

SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/CompilerOptions.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/CalciteToDBSPCompiler.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/ExpressionCompiler.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/TypeCompiler.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/DBSPCompiler.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/visitors/ToRustInnerVisitor.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/InnerVisitor.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/DBSPIndexExpression.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/expression/DBSPMatchExpression.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/ir/type/DBSPTypeVec.java
SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/ArrayTests.java
SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/BaseSQLTests.java
SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/CastTests.java
SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/ComplexQueriesTest.java
SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/EndToEndTests.java
SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/MultiViewTests.java
SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/NaiveIncrementalTests.java
SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/TimeTests.java
doc/sql.rst
doc/sql/array.rst
doc/sql/integer.rst
doc/sql/structure.rst
doc/sql/types.rst
lib/sqllib/src/casts.rs
lib/sqllib/src/lib.rs

This adds support for columns of an array type.
There still is some work needed to support nested arrays and the unnest SQL operator.
The documentation describes what the array syntax and operations available.

Initial support for array columns

---

README.md
SQL-compiler/pom.xml
SQL-compiler/run-tests.sh
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/ExpressionCompiler.java
SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/sqlparser/CalciteCompiler.java
SQL-compiler/src/main/java/org/dbsp/sqllogictest/ExecutionOptions.java
SQL-compiler/src/main/java/org/dbsp/sqllogictest/Main.java
SQL-compiler/src/main/java/org/dbsp/sqllogictest/SLTTestFile.java
SQL-compiler/src/main/java/org/dbsp/sqllogictest/SqlTestQuery.java
SQL-compiler/src/main/java/org/dbsp/sqllogictest/executors/CalciteExecutor.java
SQL-compiler/src/main/java/org/dbsp/sqllogictest/executors/DBSPExecutor.java
SQL-compiler/src/main/java/org/dbsp/sqllogictest/executors/DBSP_JDBC_Executor.java
SQL-compiler/src/main/java/org/dbsp/sqllogictest/executors/JDBCExecutor.java
SQL-compiler/src/main/java/org/dbsp/sqllogictest/executors/NoExecutor.java
SQL-compiler/src/main/java/org/dbsp/sqllogictest/executors/SqlSLTTestExecutor.java
SQL-compiler/src/main/java/org/dbsp/sqllogictest/executors/SqlTestExecutor.java
SQL-compiler/src/main/java/org/dbsp/util/StringPrintStream.java
SQL-compiler/src/main/java/org/dbsp/util/TestStatistics.java
SQL-compiler/src/main/java/org/dbsp/util/Utilities.java
SQL-compiler/src/main/java/org/dbsp/zetasqltest/Main.java
SQL-compiler/src/main/java/org/dbsp/zetasqltest/NoExecutor.java
SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/OtherTests.java
SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/postgres/PostgresTimestampTests.java

Fixes #146 
This makes it unnecessary to install and configure Postgres, the HSQLDB database is an in-memory Java database built especially for testing.

Test default calcite planner with SLT
